apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: wp-labs
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-me"

  DB_USER: "student"
  DB_PASSWORD: "student_secure_password"
  MONGO_URI: "mongodb://student:student_secure_password@mongodb:27017/wp_labs?authSource=admin"

  JWT_ACCESS_SECRET: "super_secret_access_key_change_in_prod"
  JWT_REFRESH_SECRET: "super_secret_refresh_key_change_in_prod"

  REDIS_PASSWORD: "redis_secure_password_change_in_prod"

  MINIO_ACCESS_KEY: "minio_admin"
  MINIO_SECRET_KEY: "minio_secure_password_change_in_prod"

  RABBITMQ_USER: "student"
  RABBITMQ_PASS: "student_rabbit_pass"

  YANDEX_CLIENT_ID: "put_your_yandex_client_id_here"
  YANDEX_CLIENT_SECRET: "put_your_yandex_client_secret_here"

  SMTP_HOST: "smtp.yandex.ru"
  SMTP_PORT: "465"
  SMTP_USER: "put_your_smtp_user_here"
  SMTP_PASS: "put_your_smtp_password_here"
  SMTP_FROM: "put_your_smtp_from_here"
  SMTP_SECURE: "true"
